apiVersion: apps/v1
kind: Namespace
apiVersion: v1
metadata:
  name: tp5
  labels:
    name: tp5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacos
  namespace: tp5
  labels:
    app: tacos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tacos
  template:
    metadata:
      labels:
        app: tacos
    spec:
      containers:
      - name: tacos
        image: imtoinou/ynov_tp:tacos
        ports:
        - containerPort: 80
          name: tacos-port
---
apiVersion: v1
kind: Service
metadata:
  name: tacos-service
  namespace: tp5
spec:
  selector:
    app: tacos
  ports:
  - name: tacos-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tacos-ingress
  namespace: tp5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: burgerandtacos.eatsout.com
    http:
      paths:
      - path: /tacos
        pathType: Prefix
        backend:
          service:
            name: tacos-service
            port:
              number: 80